/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex1;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kosta
 */
public class MyMember extends javax.swing.JFrame {
    // 1. 카드 레이아웃 객체를 선언.
private CardLayout card;
    /**
     * Creates new form MyMember
     */
    public MyMember() {
        initComponents();
        //2. 카드 레이아웃 객체를 생성
          card = (CardLayout) pp.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp = new javax.swing.JPanel();
        JPanel1 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listview = new javax.swing.JTextArea();
        searchtype = new javax.swing.JComboBox();
        searchvalue = new javax.swing.JTextField();
        searchview = new javax.swing.JButton();
        join = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ridv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pwdv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pp.setLayout(new java.awt.CardLayout());

        JPanel1.setBackground(new java.awt.Color(255, 204, 255));

        next.setBackground(new java.awt.Color(255, 102, 153));
        next.setText("다음페이지");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        listview.setColumns(20);
        listview.setRows(5);
        jScrollPane1.setViewportView(listview);

        searchtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "선택", "이름", "이메일", "아이디", " " }));
        searchtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtypeActionPerformed(evt);
            }
        });

        searchvalue.setText("jTextField1");
        searchvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchvalueActionPerformed(evt);
            }
        });

        searchview.setText("jButton4");
        searchview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                        .addComponent(searchtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(searchview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchview)))
                .addContainerGap())
        );

        pp.add(JPanel1, "card2");

        join.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("아이디");

        ridv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ridvActionPerformed(evt);
            }
        });

        jButton1.setText("중복검사");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("비밀번호");

        pwdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdvActionPerformed(evt);
            }
        });

        jLabel3.setText("이름");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("생년월일");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("이메일");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton2.setText("가입");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("List");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinLayout = new javax.swing.GroupLayout(join);
        join.setLayout(joinLayout);
        joinLayout.setHorizontalGroup(
            joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(joinLayout.createSequentialGroup()
                        .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(pwdv)))
                    .addGroup(joinLayout.createSequentialGroup()
                        .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(joinLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(joinLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ridv, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)))
                .addGap(45, 66, Short.MAX_VALUE))
        );
        joinLayout.setVerticalGroup(
            joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ridv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(joinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pp.add(join, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement pstm = null;
        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("드라이버 로딩 성공");
            String url = "jdbc:oracle:thin:@localhost:1521/pdborcl";
            String user = "kosta86";
            String pass = "new14";
            con = DriverManager.getConnection(url, user, pass);
            String num = ridv.getText().trim();
            String rid = pwdv.getText().trim();
            String rname = jTextField3.getText().trim();
            String pwd = jTextField4.getText().trim();

            StringBuffer sql = new StringBuffer();
            sql.append("insert into member values(");
            sql.append("member_seq.nextval,?,?,?,?,?,sysdate)");

            pstm = con.prepareStatement(sql.toString());

            pstm.setString(1, "xman");
            pstm.setString(2, "xman00");
            pstm.setString(3, "김길동");
            pstm.setString(4, "20000909");
            pstm.setString(5, "aa@a.com");
            pstm.executeUpdate();
        } catch (ClassNotFoundException ex) {
            System.out.println("드라이버 로딩 실패");
            ex.printStackTrace();
        } catch (SQLException ex) {
            System.out.println("오라클 에러");
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void ridvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ridvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ridvActionPerformed

    private void pwdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdvActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String idv = ridv.getText().trim();
        int resNum = findIdResult(idv);
        String msg = "";
        if (resNum > 0) {
            msg = "이미 존재하는 아이디입니다.";
            JOptionPane.showMessageDialog(this, msg);
            ridv.setText("");
            ridv.requestFocus();

        } else {
            msg = "이사용 가능한 아이디 입니다.";
            JOptionPane.showMessageDialog(this, msg);
            pwdv.requestFocus(); // 다음칸으로 포커스 이동
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
           
                card.show(pp, "card3");
                
       
       
    
    }//GEN-LAST:event_nextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        card.show(pp, "card2");

  getList();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchvalueActionPerformed

    private void searchviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchviewActionPerformed
        // TODO add your handling code here:
        String type = searchtype.getSelectedItem().toString().trim();
        String sv = searchvalue.getText().trim();
        String st = "";
        if(type.equals("이름")){
            st="rname";
        } else if(type.equals("이메일")){
            st = "email";
            }else if (type.equals("아이디")){
                st= "rid";
        }
        getSearch(sv,st);
         listview.setText("");
        Connection con = null;
        PreparedStatement pstm = null;
        ResultSet rs = null; 
    try {
        Class.forName("Oracle.jdbc.driver.OracleDriver");
        String url = "jdbc:oracle:thin:@localhost:1521/pdborcl";
        String user = "kosta86";
        String pass = "new14";
        con = DriverManager.getConnection(url, user, pass);
        StringBuffer sql = new StringBuffer();
        sql.append("select * from member");
        sql.append("where ").append(st).append(" like");
        sql.append("?");
        sql.append("order by num desc");
        pstm = con.prepareStatement(sql.toString());
        rs = pstm.executeQuery();
        while(rs.next()){
            //num, rid, rname, birth,email,rdate
            listview.append("번호" +  rs.getInt("num")+ "\n");
            listview.append("아이디" + rs.getString("rid") + "\n");
            listview.append("이름" + rs.getString("rname" + "\n"));
            listview.append("생일 " + rs.getString("birth") + "\n");
            listview.append("이메일"  + rs.getString("email") + "\n");
            listview.append("날짜" + rs.getString("rdate") + "\n");
            listview.append("============================="+ "\n");
        }
    } 
    catch (ClassNotFoundException ex) {
        ex.printStackTrace();
    } 
    catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_searchviewActionPerformed

    private void searchtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtypeActionPerformed
    private int findIdResult(String idv){

        Connection con = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
 

        String url = "jdbc:oracle:thin:@localhost:1521:pdborcl";
        String user = "kosta86";
        String pass = "new14";
        int resN = 0;
        try {
            con = DriverManager.getConnection(url, user, pass);
            StringBuffer sql = new StringBuffer();
            sql.append("select count(*) cnt from member ");
            sql.append(" where rid=?");
            pstmt = con.prepareStatement(sql.toString());
            
            pstmt.setString(1, idv);
            rs = pstmt.executeQuery();
            if (rs.next()) {
                resN = rs.getInt("cnt");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return resN;
// 1. 데이터 베이스를 접속하기 위한 드라이버 로딩
        
    }
public void getList(){
        listview.setText("");
        Connection con = null;
        PreparedStatement pstm = null;
        ResultSet rs = null; 
    try {
        Class.forName("Oracle.jdbc.driver.OracleDriver");
        String url = "jdbc:oracle:thin:@localhost:1521/pdborcl";
        String user = "kosta86";
        String pass = "new14";
        con = DriverManager.getConnection(url, user, pass);
        StringBuffer sql = new StringBuffer();
        sql.append("select * from member");
        sql.append("order by num desc");
        pstm = con.prepareStatement(sql.toString());
        rs = pstm.executeQuery();
        while(rs.next()){
            //num, rid, rname, birth,email,rdate
            listview.append("번호" +  rs.getInt("num")+ "\n");
            listview.append("아이디" + rs.getString("rid") + "\n");
            listview.append("이름" + rs.getString("rname" + "\n"));
            listview.append("생일 " + rs.getString("birth") + "\n");
            listview.append("이메일"  + rs.getString("email") + "\n");
            listview.append("날짜" + rs.getString("rdate") + "\n");
            listview.append("============================="+ "\n");
        }
    } 
    catch (ClassNotFoundException ex) {
        ex.printStackTrace();
    } 
    catch (SQLException ex) {
        ex.printStackTrace();
    }

}
public void getSearch(String sv, String st){
     
    System.out.println(sv + st);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel join;
    private javax.swing.JTextArea listview;
    private javax.swing.JButton next;
    private javax.swing.JPanel pp;
    private javax.swing.JTextField pwdv;
    private javax.swing.JTextField ridv;
    private javax.swing.JComboBox searchtype;
    private javax.swing.JTextField searchvalue;
    private javax.swing.JButton searchview;
    // End of variables declaration//GEN-END:variables

 
}
